server:
  context-path: /survey2020
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/survey2020?useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update