server:
  context-path: /survey2020
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://13.69.250.36:3306/survey2020?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
